# Generated by Django 4.0.3 on 2022-04-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dse_id', models.CharField(max_length=200)),
                ('trading_code', models.CharField(max_length=200)),
                ('ltp', models.CharField(max_length=200)),
                ('highest_trade', models.CharField(max_length=200)),
                ('lowest_trade', models.CharField(max_length=200)),
                ('closeP', models.CharField(max_length=200)),
                ('ycp', models.CharField(max_length=200)),
                ('change', models.CharField(max_length=200)),
                ('trade', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('volume', models.CharField(max_length=200)),
            ],
        ),
    ]
